#!/bin/bash

if [ $# -lt 1 ]; then
    echo "usage: run <port>";
    exit 1;
fi

set -x;

docker run \
    --rm \
    --detach \
    --name gitsense-app \
    --volume gitsense-app-opt:/opt \
    --volume gitsense-app-home:/home/gitsense \
    --publish ${1}:3357 \
    gitsense-app
