#!/bin/bash

if [ $# -gt 1 ]; then
    echo "usage: run [port]";
    exit 1;
fi

if [ -z "${1}" ]; then
    port=3357;
else
    port=$1;
fi

set -x;

docker run \
    --rm \
    --detach \
    --name gitsense-app \
    --volume gitsense-app-opt:/opt \
    --volume gitsense-app-home:/home/gitsense \
    --publish ${port}:3357 \
    gitsense/app
